### ISSUE TITLE
Verify ALL backups before June 1st

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/kube-infra#14]
One all backups have been running as cronjobs in K8s for a little while, we need to verify the contents of all them to ensure they are producing recoverable data. 

Manually verify the content of the backups is valid:
- [x] Postgress
- [x] Consul
- [x] ETCD
- [ ] MongoDB

**Comment by akachru-github** [comment]
@andricDu / @henro001 , would restoring the backups into Staging be a viable test for this ticket?

**Comment by andricDu** [comment]
@akachru-github That would be the final step. The first step should be to inspect the backups by hand and see if they can be restored to a local mongodb/postgres. This should short circuit immediately in the case of bad backups so we don't waste time with k8s, and also ensure in case of disaster recovery our backups work independent of k8s.

**Comment by henro001** [comment]
I use some verification for etcd and consul:

https://wiki.oicr.on.ca/display/icgcargotech/Kube+backups

**Comment by akachru-github** [comment]
As discussed on Friday May 22, we had verified the following: 
- Consul
- ETCD
- Postgress

The only outstanding backups that require content verification are the MongoDB backups, which @andricDu will take a look at. I will assign this ticket over to Dusan for the final manual check of the mongo backups we have been taking. Once verified, we can close this ticket out.

**Comment by andricDu** [comment]
I have re validated a full restore of Ego from its latest backup.

**Comment by andricDu** [comment]
mongo restored validated by doing mongorestore
